spring.application.name=nutrition-tracker
# Cloud providers like Render assign a dynamic port. We default to 8085 locally.
server.port=${PORT:8085}

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://samsameer2804_db_user:RRaXqjQcP2BUIRDg@cluster0.msctkk7.mongodb.net/nutritiondb?retryWrites=true&w=majority&appName=Cluster0

# CORS Configuration for the frontend
spring.mvc.cors.allowed-origins=*
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
